name: Haus Scholia
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
pygments: true
permalink: /:categories/:title
prose:
  rooturl: '_posts'
  siteurl: 'http://hausscholia.net'
  media: 'media'
  metadata:
    _posts/posts:
      - name: "categories"
        field:
          element: "hidden"
          value: "posts"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
    _posts/members:
      - name: "categories"
        field:
          element: "hidden"
          value: "members"
      - name: "layout"
        field:
          element: "hidden"
          value: "member"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
