name: Haus Of Scholia
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
pygments: true

roster:
- name: Neranna Taitar
  title: Duchess
  race: Human
  profession: Thief
  bio:
  crafts:
  - craft: Cook
  - craft: Huntsman
- name: Vakanya Dolshynya
  title: Duchess
  race: Norn
  profession: Warrior
  bio:
  crafts:
  - craft: Armorsmith
  - craft: Weaponsmith
- name: Yori Lawr
  title: Duchess
  race: Norn
  profession: Mesmer
  bio:
  crafts:
  - craft: Artificer
  - craft: Jeweler
- name: Akaria Rubeathin
  title: Duchess
  race: Human
  profession: Necromancer
  bio:
  crafts:
  - craft: Tailor
- name: Serigga
  title: Duchess
  race: Asura
  profession: Guardian
  bio:
  crafts:
- name: Feairraelly Shaeln
  title: Duchess
  race: Norn
  profession: Ranger
  bio:
  crafts:
  - craft: Leatherworker
- name: Zendella
  title: Dame
  race: Human
  profession: Mesmer
  bio:
  crafts:
- name: Karistany
  title: Dame
  race: Human
  profession: Guardian
  bio:
  crafts:
- name: Selia Jade
  title: Dame
  race: Sylvari
  profession: Necromancer
  bio:
  crafts:
- name: Ash Clawburn
  title: Baron
  race: Charr
  profession: Engineer
  bio:
  crafts:
  - craft: Huntsman
  - craft: Leatherworker
- name: Eoghan the Limber
  title: Baron
  race: Sylvari
  profession: Thief
  bio:
  crafts:
- name: Daeron Falconer
  title: Knight
  race: Human
  profession: Warrior
  bio:
  crafts:
- name: Brand Formion
  title: Knight
  race: Norn
  profession: Ranger
  bio:
  crafts:
- name: Ithronaru
  title: Knight
  race: Asura
  profession: Elementalist
  bio:
  crafts:
- name: Vorastrasa
  title: Duke
  race: Human
  profession: Necromancer
  bio:
  crafts:
- name: Valastor
  title: Duke
  race: Human
  profession: Mesmer
  bio:
  crafts:
